#! /bin/sh

set -x
# cleanup should not be necessary
# however, in some cases strange results are found if you do not start clean
rm -rf autom4te.cache
rm -f aclocal.m4
rm -f Makefile.in */Makefile.in */defs.h.in
rm -f missing install-sh depcomp 
rm -f configure config.*
# run autotool commands
aclocal 
autoheader
automake --add-missing --copy
autoconf

# To avoid confusing people with failures in the documentation build, 
# build documents during the bootstrap process.
OS=`uname`
if [ $OS = "Darwin" ]; then
  OSname=`uname -s`
else
  OSname=`uname -o`
fi
if [ $OSname != "Cygwin" ]; then
  cd doc; ./buildDoc.sh
fi

# ready to make a source code distribution tarball
