#! /bin/sh

set -x
# cleanup should not be necessary
# however, in some cases strange results are found if you do not start clean
rm -rf autom4te.cache
rm -f aclocal.m4
rm -f Makefile.in */Makefile.in */defs.h.in
rm -f missing install-sh depcomp 
rm -f configure config.*
# run autotool commands
aclocal 
autoheader
automake --add-missing --copy
autoconf

# ready to make a source code distribution tarball
